name: elapsed_time_element
version: 0.12.1
author: Jim Heyne <jheyne@gmail.com>
homepage: https://github.com/jheyne/elapsed_time_element
description: Dart Polymer component displaying elapsed time for a DateTime instance. For example, 1 day 2 hours 3 minutes.
dependencies:
  core_elements: any
  intl: any
  polymer: any
dev_dependencies:
  unittest: any
transformers:
- polymer:
    entry_points:
    - example/app.html
